.TH MYSTRCAT 3 "September 2026" "libmyutils 1.0" "libmyutils Manual"
.SH NAME
mystrcat \- concatenate two strings
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.sp
.BI "int mystrcat(char *" dest ", const char *" src ");"
.SH DESCRIPTION
The
.B mystrcat()
function appends a copy of the string pointed to by
.I src
to the end of the string pointed to by
.IR dest .
The caller must ensure
.I dest
has enough space for the combined result.
.SH RETURN VALUE
Returns the new length of
.I dest
after concatenation.
.SH AUTHOR
Asmara456 (asmaramehboob@gmail.com)
